version: '3'

services:
  web:
    build:
      context: .
    ports:
    - 5000:5000
    volumes:
    - ./:/app

  mongodb:
    image: mongo
    ports:
    - 27018:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo: